import Head from "next/head";
import { Header } from "../components/Header/Header";
import { Products } from "../components/Products/Produts";
import { Unversity } from "../components/Unversity/Unversity";

export default function Home() {
  return (
    <div>
      <Head>
        <title>WiseSpace</title>
        <meta name="description" content="Generated by © 2022 Wisespace.uz" />
        <link rel="icon" href="/icons/logo.svg" />
      </Head>
      <main>
        <Header />
        <Unversity />
        <Products />
      </main>
      <footer></footer>
    </div>
  );
}
